# Increase memory for the build process
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8

# Disable the Kotlin Daemon to fix RMI "no such object in table" errors
kotlin.compiler.execution.strategy=in-process

android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=false
